<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * PictureRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends \Doctrine\ORM\EntityRepository
{
    const NB_PER_PAGE = 20;

    public function getList($page = 1, $nbMax = self::NB_PER_PAGE)
    {
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.createdAt', 'DESC');

        $query = $qb->getQuery();

        $results = ($page - 1) * $nbMax;
        $query->setFirstResult($results)->setMaxResults($nbMax);
        $paginator = new Paginator($query);

        if (($paginator->count() <= $results) && $page != 1) {
            throw new NotFoundHttpException(); // page 404, sauf pour la première page
        }

        return $paginator;
    }
}
